//apply plugin: 'com.android.application'

plugins {
        id 'com.android.application'
    }



android {
    namespace = 'com.git.amarradi.leafpad'
    compileSdk = 36

    defaultConfig {
        applicationId = "com.git.amarradi.leafpad"
        minSdkVersion 25
        targetSdkVersion 36
        versionCode = 31
        versionName = "1.23"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        resourceConfigurations += [
                'aeb',  // Tunisian Arabic
                'ar',  // Arabic
                'ar-rEG',  // Egyptian Arabic
                'be',  // Belarusian
                'bg',  // Bulgarian
                'br',  // Breton
                'ca',  // Catalan
                'ce',  // Chechen
                'cs',  // Czech
                'da',  // Danish
                'de',  // German
                'el',  // Greek
                'en',  // English
                'en-rGB',
                'es',  // Spanish
                'et',  // Estonian
                'fi',  // Finnish
                'fr',  // French
                'got',  // Gothic (ISO 639-3)
                'hi',  // Hindi (Devanagari)
                'hu',  // Hungarian
                'id',  // Indonesian
                'it',  // Italian
                'nb',  // Norwegian Bokmål
                'nl',  // Dutch
                'pl',  // Polish
                'pt',  // Portuguese
                'ru',  // Russian
                'sq',  // Albanian
                'sr', // Serbian
                'sv',  // Swedish
                'ta',  // Tamil
                'uk',  // Ukrainian
                'ur',  // Urdu
                'uz',  // Uzbek
                'zh-rCN',  // Chinese (Simplified)
                'zh-rTW',  // Chinese (Traditional)
                'b+hi+Latn',  // BCP-47: Hindi (Latin)
        ]


        //version types: alpha, beta, r
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    namespace = 'com.git.amarradi.leafpad'
    buildToolsVersion = '35.0.0'
    buildFeatures {
        viewBinding = true
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }

    applicationVariants.all { variant ->
        if (variant.buildType.name == "release") {
            variant.outputs.all { output ->
                def apkName = "app-release.apk"
                outputFileName = apkName
            }
        }
    }
}

dependencies {

//    implementation 'androidx.navigation:navigation-fragment:2.9.7'
//    implementation 'androidx.navigation:navigation-ui:2.9.7'

    def core = "1.18.0"
    def coordinatorLayout = "1.3.0"
    def appcompat = "1.7.1"
    def material = "1.13.0"
    def splashscreen = "1.2.0"
    def constraintlayout = "2.2.1"
    def preference_version = "1.2.1"
    def activity_version = '1.13.0'
    def lifecycle = '2.9.0'
//    def roomcommonjvm = '2.8.3'
//    def roomruntime1 = '2.8.3'
    def room = '2.8.4'
//    def roomcompiler1 = '2.8.3'
//    def roomcompiler2 = '2.8.4'
    def colorpicker = '1.1.0'


    implementation "androidx.core:core:$core"
    implementation "androidx.coordinatorlayout:coordinatorlayout:$coordinatorLayout"
    implementation "androidx.appcompat:appcompat:$appcompat"
    implementation "com.google.android.material:material:$material"
    implementation "androidx.core:core-splashscreen:$splashscreen"
    implementation "androidx.constraintlayout:constraintlayout:$constraintlayout"
    implementation "androidx.preference:preference:$preference_version"
    implementation "androidx.activity:activity:$activity_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel:$lifecycle"
//    implementation "androidx.room:room-common-jvm:$roomcommonjvm"
//    implementation "androidx.room:room-runtime:$roomruntime1"
    implementation "androidx.room:room-runtime:$room"
    annotationProcessor "androidx.room:room-compiler:$room"
//    annotationProcessor "androidx.room:room-compiler:$roomcompiler2"
    implementation "com.jaredrummler:colorpicker:$colorpicker"

}
